---
header-includes:
    - \usepackage{fancyhdr}
    - \fancyfoot[CO,CE]{OSC-Group - http://www.osc-lab.de - JMU Wuerzburg - Pharmazie}
    - \fancyfoot[LE,RO]{\thepage}
    - \usepackage{lscape}
    - \newcommand{\blandscape}{\begin{landscape}}
    - \newcommand{\elandscape}{\end{landscape}}

title: "DBSconvertR v0.0.1 Report"
output:
  pdf_document:
  latexengine: xelatex
df_print: paged
date: "`r format(Sys.time(), '%d.%B %Y')`"


---
\addtolength{\headheight}{1.0cm}
\pagestyle{fancyplain}
\renewcommand{\headrulewidth}{0pt}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Conversion method: **`r input$method`**

`r app_data$current_settings`

\newpage

# **Observations** 

```{r raw_data, echo=FALSE, warning=FALSE, fig.height = 5, fig.width = 10, fig.align = "center"}
app_data$current_obs_plot
```


# **Bland Altman Plot** 

```{r bland_alt, echo=FALSE, warning=FALSE, fig.height = 5, fig.width = 10, fig.align = "center"}
app_data$current_bland_altman_plot
```

\newpage


# **Passing Bablok Regression** 

```{r paBa_reg, echo=FALSE, warning=FALSE, fig.height = 5, fig.width = 10, fig.align = "center"}
app_data$current_passing_bablok_plot
```

```{r paBa_reg_2, echo=FALSE, warning=FALSE, fig.height = 5, fig.width = 10, fig.align = "center"}
app_data$current_passing_bablok_plot_2
```

\newpage

# **Deming Regression** 

```{r dem_reg, echo=FALSE, warning=FALSE, fig.height = 5, fig.width = 10, fig.align = "center"}
app_data$current_deming_plot
```

```{r dem_reg_2, echo=FALSE, warning=FALSE, fig.height = 5, fig.width = 10, fig.align = "center"}
app_data$current_deming_plot_2
```

\newpage

# **Dataset**

``` {r tdm_cov, echo=FALSE, warning=FALSE}

kable(app_data$current_dataset, format = "latex")  %>%
    kable_styling(position = "left")

```

